server:
  port: 8080

spring:
  application:
    name: order
  # zookeeper 配置中心
#  cloud:
#    zookeeper:
#      connect-string: 127.0.0.1:2181
#    consul:
#      host: 127.0.0.1
#      port: 8500
#      discovery:
#        service-name: ${spring.application.name}
#        prefer-ip-address: true
feign:
  client:
    config:
      default:
       connectTimeout: 30000
       readTimeout: 30000
       loggerLevel: FULL
eureka:
  client:
    #表示是否将自己注册进EurekaServer默认为true
    register-with-eureka: true
    #是否从EurekaServer抓取已有的注册信息，默认为true。单节点无所谓，集群必须设置为true才能配合ribbon使用 负载均衡
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:7001.com/eureka,http://localhost:7002/eureka
  instance:
    instance-id: ${spring.application.name}:${server.port}
    prefer-ip-address: true
    ip-address: 127.0.0.1
logging:
  level:
    com.mxp: debug
